# Generated by Django 3.1.7 on 2021-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_auto_20210330_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='header_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(default='', max_length=200),
        ),
    ]
